FROM centos:7.1.1503
MAINTAINER Docker johnhouzheng@gmail.com
# add group and user
RUN groupadd -r light && useradd -r -g light light

COPY tar /bin/tar

RUN yum update -y

# install redis and dependance app
RUN yum install -y gcc zip unzip make perl python-setuptools ncurses-devel ncruses-devel wget xmlto 

RUN easy_install supervisor

# install redis
RUN wget -r --no-parent -A'epel-release-*.rpm' http://dl.fedoraproject.org/pub/epel/7/x86_64/e/

RUN rpm -Uvh dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-*.rpm

RUN yum install -y redis

# install erlang
RUN wget http://www.erlang.org/download/otp_src_17.5.tar.gz

RUN tar zxvf otp_src_17.5.tar.gz \
    && cd otp_src_17.5 \
    && ./configure \
    && make \
    && make install

# install rabbitmq
RUN wget http://www.rabbitmq.com/releases/rabbitmq-server/v3.5.1/rabbitmq-server-3.5.1.tar.gz

RUN tar zxvf rabbitmq-server-3.5.1.tar.gz \
    && cd rabbitmq-server-3.5.1 \
    && make TARGET_DIR=/usr/rabbitmq SBIN_DIR=/usr/rabbitmq/sbin MAN_DIR=/usr/rabbitmq/man DOC_INSTALL_DIR=/usr/rabbitmq/doc \ 
    && make TARGET_DIR=/usr/rabbitmq SBIN_DIR=/usr/rabbitmq/sbin MAN_DIR=/usr/rabbitmq/man DOC_INSTALL_DIR=/usr/rabbitmq/doc install

# add user to rabbitmq
RUN /usr/rabbitmq/sbin/rabbitmq-server -detached
RUN /usr/rabbitmq/sbin/rabbitmqctl add_user admin admin \
    && /usr/rabbitmq/sbin/rabbitmqctl set_user_tags admin administrator

# clean 
RUN rm otp_src_17.5.tar.gz \
    && rm rabbitmq-server-3.5.1.tar.gz \
    && rm -r otp_src_17.5 \
    && rm -r rabbitmq-server-3.5.1 

# prepare
RUN mkdir /redisdata && chown light:light /redisdata\
    && mkdir -p /var/log/supervisor
    && sed -i 's/daemonize no/daemonize yes/g' /etc/redis.conf    

VOLUME /redisdata

COPY supervisord.conf /etc/supervisord.conf

EXPOSE 6379 5672

CMD ["/usr/bin/supervisord"]

